sudo: required
language: node_js

git:
  depth: 1

cache:
  yarn: true
  directories:
    - ./node_modules

addons:
  apt:
    sources:
      - google-chrome
    packages:
      - google-chrome-stable

env:
  - TASK=build
  - TASK=test
  - TASK=lint
  - TASK=site:build

script:
  - npm run $TASK
