sudo: required
dist: trusty
language: node_js

git:
  depth: 1

cache:
  yarn: true
  directories:
    - ./node_modules

before_install:
  - set -e
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - sleep 3
  - export NG_CLI_ANALYTICS=ci

addons:
  apt:
    sources:
      - google-chrome
    packages:
      - google-chrome-stable

env:
  - TASK=build
  - TASK=test
  - TASK=lint
  - TASK=site:build

script:
  - npm run $TASK
